Data vis
lab11/soil-battery pull request #4
Opened 2020-11-23 22:36 UTC by chpmk98

data visualization and sample data for TEROS loggers

2020-11-23 22:40 UTC, brghena commented on .gitignore
> +/matlab/data/*.DS_Store
Definitely needs to be on a separate line

2020-11-24 21:57 UTC, cjosephson requested changes
I don't think data_processing/data/teros/TEROSoutput-1605757252-f7.csv should be added, can you remove it?

Also, wasn't there an entire separate PR for the changes in teroslogger.c?

2020-11-25 03:59 UTC, chpmk98 commented
Removed the data file.

Yeah, the teroslogger.c update was in a logger PR that you already merged

2020-12-03 13:58 UTC, cjosephson approved these changes

2020-12-03 13:59 UTC, merged